/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registrazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrazione */
        post: operations["registrazione_api_v1_auth_registrazione_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comuni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comuni */
        get: operations["comuni_api_v1_comuni_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Stato del servizio, usato da monitoraggio e smoke test.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_hosts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia Password */
        post: operations["cambia_password_api_v1_hosts_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me/preferenze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna Preferenze */
        patch: operations["aggiorna_preferenze_api_v1_hosts_me_preferenze_patch"];
        trace?: never;
    };
    "/api/v1/interno/comuni/{codice_istat}/configurazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configura Comune */
        put: operations["configura_comune_api_v1_interno_comuni__codice_istat__configurazione_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/parametri-fiscali": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configura Parametri Fiscali
         * @description Soglia e testi del Regime fiscale: dati, non costanti (AD-12).
         */
        put: operations["configura_parametri_fiscali_api_v1_interno_parametri_fiscali_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/regioni/{codice_istat}/configurazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configura Regione */
        put: operations["configura_regione_api_v1_interno_regioni__codice_istat__configurazione_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime-fiscale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regime Fiscale
         * @description Regime fiscale derivato dal numero di Strutture non archiviate.
         */
        get: operations["regime_fiscale_api_v1_regime_fiscale_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime-fiscale/conferma-lettura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conferma Lettura
         * @description L'Host ha letto il pannello a schermo intero (UX-DR14).
         */
        post: operations["conferma_lettura_api_v1_regime_fiscale_conferma_lettura_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regioni
         * @description Anagrafica pubblica: serve anche prima dell'accesso (form di onboarding).
         */
        get: operations["regioni_api_v1_regioni_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista */
        get: operations["lista_api_v1_strutture_get"];
        put?: never;
        /** Crea */
        post: operations["crea_api_v1_strutture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna */
        patch: operations["aggiorna_api_v1_strutture__struttura_id__patch"];
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}/archivia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archivia */
        post: operations["archivia_api_v1_strutture__struttura_id__archivia_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}/configurazione-normativa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configurazione Normativa
         * @description Configurazione applicabile alla Struttura, con degrado sicuro (AD-9).
         */
        get: operations["configurazione_normativa_api_v1_strutture__struttura_id__configurazione_normativa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaIstatOutput */
        AreaIstatOutput: {
            /** Messaggio */
            messaggio: string;
            motivo: components["schemas"]["Motivo"] | null;
            parametri: components["schemas"]["ParametriIstatOutput"] | null;
            /** Promemoria Manuale */
            promemoria_manuale: boolean;
            stato: components["schemas"]["StatoConfigurazione"];
        };
        /** AreaTassaOutput */
        AreaTassaOutput: {
            /** Messaggio */
            messaggio: string;
            motivo: components["schemas"]["Motivo"] | null;
            parametri: components["schemas"]["ParametriTassaOutput"] | null;
            /** Promemoria Manuale */
            promemoria_manuale: boolean;
            stato: components["schemas"]["StatoConfigurazione"];
        };
        /** CambioPasswordInput */
        CambioPasswordInput: {
            /** Password Attuale */
            password_attuale: string;
            /** Password Nuova */
            password_nuova: string;
        };
        /**
         * CanaleNotifica
         * @description Canali di notifica Host dell'MVP (envelope operativo: in-app + email).
         * @enum {string}
         */
        CanaleNotifica: "in_app" | "email";
        /** ComuneConfigInput */
        ComuneConfigInput: {
            /** Attore */
            attore: string;
            /** Esenzione Eta Max */
            esenzione_eta_max?: number | null;
            /** Esenzione Notti Oltre */
            esenzione_notti_oltre?: number | null;
            /** Tassa Importo Cent */
            tassa_importo_cent: number;
            tassa_periodicita: components["schemas"]["Periodicita"];
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ComuneOutput */
        ComuneOutput: {
            /** Codice Istat */
            codice_istat: string;
            /** Nome */
            nome: string;
            /** Provincia */
            provincia: string;
            /** Regione Codice Istat */
            regione_codice_istat: string;
        };
        /** ConfigSalvataOutput */
        ConfigSalvataOutput: {
            /** Valido Al */
            valido_al: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ConfigurazioneNormativaOutput */
        ConfigurazioneNormativaOutput: {
            /**
             * Alla Data
             * Format: date
             */
            alla_data: string;
            istat: components["schemas"]["AreaIstatOutput"];
            tassa_soggiorno: components["schemas"]["AreaTassaOutput"];
        };
        /** CredenzialiInput */
        CredenzialiInput: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostOutput */
        HostOutput: {
            canale_notifica_preferito: components["schemas"]["CanaleNotifica"];
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * Motivo
         * @enum {string}
         */
        Motivo: "comune_non_riconosciuto" | "comune_non_configurato" | "regione_non_riconosciuta" | "regione_non_configurata";
        /** ParametriFiscaliInput */
        ParametriFiscaliInput: {
            /** Aliquote Citate */
            aliquote_citate: string;
            /** Attore */
            attore: string;
            /** Regime Da Soglia */
            regime_da_soglia: string;
            /** Regime Sotto Soglia */
            regime_sotto_soglia: string;
            /** Soglia Strutture */
            soglia_strutture: number;
            /** Testo Da Soglia */
            testo_da_soglia: string;
            /** Testo Sotto Soglia */
            testo_sotto_soglia: string;
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ParametriIstatOutput */
        ParametriIstatOutput: {
            periodicita: components["schemas"]["Periodicita"];
            /** Tracciato */
            tracciato: string;
        };
        /** ParametriTassaOutput */
        ParametriTassaOutput: {
            /** Esenzione Eta Max */
            esenzione_eta_max: number | null;
            /** Esenzione Notti Oltre */
            esenzione_notti_oltre: number | null;
            /** Importo Cent */
            importo_cent: number;
            periodicita: components["schemas"]["Periodicita"];
        };
        /**
         * Periodicita
         * @enum {string}
         */
        Periodicita: "mensile" | "trimestrale" | "semestrale" | "annuale";
        /** PreferenzeInput */
        PreferenzeInput: {
            canale_notifica_preferito: components["schemas"]["CanaleNotifica"];
        };
        /**
         * RegimeFiscaleOutput
         * @description Contenuto informativo con disclaimer: mai un calcolo d'imposta.
         */
        RegimeFiscaleOutput: {
            /** Aliquote Citate */
            aliquote_citate: string | null;
            /** Disclaimer */
            disclaimer: string;
            /** Mostra Pannello Transizione */
            mostra_pannello_transizione: boolean;
            /** Oltre Soglia */
            oltre_soglia: boolean;
            /** Regime */
            regime: string | null;
            /** Soglia */
            soglia: number | null;
            stato: components["schemas"]["StatoRegime"];
            /** Strutture Non Archiviate */
            strutture_non_archiviate: number;
            /** Testo */
            testo: string;
        };
        /** RegioneConfigInput */
        RegioneConfigInput: {
            /** Attore */
            attore: string;
            istat_periodicita: components["schemas"]["Periodicita"];
            /** Istat Tracciato */
            istat_tracciato: string;
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** RegioneOutput */
        RegioneOutput: {
            /** Codice Istat */
            codice_istat: string;
            /** Nome */
            nome: string;
        };
        /**
         * StatoConfigurazione
         * @enum {string}
         */
        StatoConfigurazione: "configurata" | "configurazione_non_disponibile";
        /**
         * StatoRegime
         * @enum {string}
         */
        StatoRegime: "disponibile" | "configurazione_non_disponibile";
        /**
         * StatoStruttura
         * @description Una Struttura si archivia, mai si distrugge (AD-20).
         * @enum {string}
         */
        StatoStruttura: "attiva" | "archiviata";
        /** StrutturaInput */
        StrutturaInput: {
            /** Cin */
            cin?: string | null;
            /** Comune */
            comune: string;
            /** Comune Codice Istat */
            comune_codice_istat?: string | null;
            /** Nome */
            nome: string;
            /** Regione */
            regione: string;
        };
        /** StrutturaOutput */
        StrutturaOutput: {
            /** Cin */
            cin: string | null;
            /** Cin Mancante */
            readonly cin_mancante: boolean;
            /** Comune */
            comune: string;
            /** Comune Codice Istat */
            comune_codice_istat: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
            /** Regione */
            regione: string;
            /** Regione Codice Istat */
            regione_codice_istat: string | null;
            stato: components["schemas"]["StatoStruttura"];
        };
        /** StrutturaUpdate */
        StrutturaUpdate: {
            /** Cin */
            cin?: string | null;
            /** Comune */
            comune?: string | null;
            /** Comune Codice Istat */
            comune_codice_istat?: string | null;
            /** Nome */
            nome?: string | null;
            /** Regione */
            regione?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredenzialiInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registrazione_api_v1_auth_registrazione_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredenzialiInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comuni_api_v1_comuni_get: {
        parameters: {
            query: {
                ricerca: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComuneOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_v1_hosts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
        };
    };
    cambia_password_api_v1_hosts_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioPasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggiorna_preferenze_api_v1_hosts_me_preferenze_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenzeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_comune_api_v1_interno_comuni__codice_istat__configurazione_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                codice_istat: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComuneConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_parametri_fiscali_api_v1_interno_parametri_fiscali_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParametriFiscaliInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_regione_api_v1_interno_regioni__codice_istat__configurazione_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                codice_istat: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegioneConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regime_fiscale_api_v1_regime_fiscale_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeFiscaleOutput"];
                };
            };
        };
    };
    conferma_lettura_api_v1_regime_fiscale_conferma_lettura_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regioni_api_v1_regioni_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegioneOutput"][];
                };
            };
        };
    };
    lista_api_v1_strutture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"][];
                };
            };
        };
    };
    crea_api_v1_strutture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrutturaInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggiorna_api_v1_strutture__struttura_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrutturaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archivia_api_v1_strutture__struttura_id__archivia_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configurazione_normativa_api_v1_strutture__struttura_id__configurazione_normativa_get: {
        parameters: {
            query?: {
                alla_data?: string | null;
            };
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurazioneNormativaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
