/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registrazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrazione */
        post: operations["registrazione_api_v1_auth_registrazione_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Griglia
         * @description Il calendario unificato di un periodo (FR-4, UJ-1).
         *
         *     `struttura_id` assente = vista aggregata su tutte le Strutture; presente
         *     = una sola Struttura. È lo stesso endpoint, ed è il motivo per cui il
         *     selettore di UX-DR1 filtra senza cambiare schermata: cambia un parametro
         *     di query, non la superficie.
         */
        get: operations["griglia_api_v1_calendario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comuni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comuni */
        get: operations["comuni_api_v1_comuni_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-ical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista */
        get: operations["lista_api_v1_feed_ical_get"];
        put?: never;
        /**
         * Collega
         * @description Collega un Feed e accoda subito l'import (AD-4, AD-10).
         */
        post: operations["collega_api_v1_feed_ical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-ical/{feed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dettaglio */
        get: operations["dettaglio_api_v1_feed_ical__feed_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-ical/{feed_id}/prenotazioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prenotazioni
         * @description Prenotazioni importate dal Feed, comprese quelle non più attive.
         *
         *     Una Prenotazione uscita da `attiva` resta visibile: farla sparire senza
         *     traccia contraddirebbe «archiviare, mai distruggere» agli occhi dell'Host
         *     (AD-20).
         *
         *     La risposta porta con sé lo stato di sincronizzazione e l'orario
         *     dell'ultimo sync riuscito: questa è una superficie che mostra dati da
         *     Feed, e UX-DR6 vuole «dati aggiornati alle HH:MM» su ognuna. La guardia
         *     `tests/test_superfici_feed_convention.py` (GS-7) impone che resti vero
         *     anche per le superfici che non esistono ancora.
         */
        get: operations["prenotazioni_api_v1_feed_ical__feed_id__prenotazioni_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Stato del servizio, usato da monitoraggio e smoke test.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_hosts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia Password */
        post: operations["cambia_password_api_v1_hosts_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/me/preferenze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna Preferenze */
        patch: operations["aggiorna_preferenze_api_v1_hosts_me_preferenze_patch"];
        trace?: never;
    };
    "/api/v1/interno/comuni/{codice_istat}/configurazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configura Comune */
        put: operations["configura_comune_api_v1_interno_comuni__codice_istat__configurazione_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/host/{host_id}/azzeramento-ospiti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Azzera Ospiti Dell Host
         * @description Azzera i campi personali di TUTTI gli Ospiti di un Host (NFR-15).
         *
         *     Resta dentro il perimetro di quell'Host (AD-2): non esiste una forma
         *     «tutti gli Host», e non è una dimenticanza.
         */
        post: operations["azzera_ospiti_dell_host_api_v1_interno_host__host_id__azzeramento_ospiti_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/host/{host_id}/ospiti/{ospite_id}/azzeramento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Azzera Ospite
         * @description Azzera i campi personali di UN Ospite su richiesta (NFR-15, AD-21).
         *
         *     Riusa la procedura del job di retention: cambia la selezione, non
         *     l'azzeramento. Mai una `DELETE` — sarebbe una quarta forma distruttiva
         *     fuori dalla lista esaustiva di AD-20, e GS-6 la fermerebbe.
         *
         *     L'Ospite sta sotto il suo Host anche nel percorso: la tenancy di un
         *     endpoint senza sessione deve essere scritta da qualche parte, e il
         *     percorso è il posto in cui si vede (AD-2).
         */
        post: operations["azzera_ospite_api_v1_interno_host__host_id__ospiti__ospite_id__azzeramento_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/parametri-fiscali": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configura Parametri Fiscali
         * @description Soglia e testi del Regime fiscale: dati, non costanti (AD-12).
         */
        put: operations["configura_parametri_fiscali_api_v1_interno_parametri_fiscali_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interno/regioni/{codice_istat}/configurazione": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configura Regione */
        put: operations["configura_regione_api_v1_interno_regioni__codice_istat__configurazione_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime-fiscale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regime Fiscale
         * @description Regime fiscale derivato dal numero di Strutture non archiviate.
         */
        get: operations["regime_fiscale_api_v1_regime_fiscale_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime-fiscale/conferma-lettura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conferma Lettura
         * @description L'Host ha letto il pannello a schermo intero (UX-DR14).
         */
        post: operations["conferma_lettura_api_v1_regime_fiscale_conferma_lettura_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regioni
         * @description Anagrafica pubblica: serve anche prima dell'accesso (form di onboarding).
         */
        get: operations["regioni_api_v1_regioni_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista */
        get: operations["lista_api_v1_strutture_get"];
        put?: never;
        /** Crea */
        post: operations["crea_api_v1_strutture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna */
        patch: operations["aggiorna_api_v1_strutture__struttura_id__patch"];
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}/archivia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archivia */
        post: operations["archivia_api_v1_strutture__struttura_id__archivia_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strutture/{struttura_id}/configurazione-normativa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configurazione Normativa
         * @description Configurazione applicabile alla Struttura, con degrado sicuro (AD-9).
         */
        get: operations["configurazione_normativa_api_v1_strutture__struttura_id__configurazione_normativa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmbitoAzzeramento
         * @description Su chi è stato chiesto l'azzeramento (NFR-15).
         *
         *     Due soli valori, e sono il perimetro che AD-21 ammette per la
         *     cancellazione su richiesta: un singolo Ospite, oppure tutti gli Ospiti di
         *     un Host. Il secondo resta dentro quell'Host (AD-2): non esiste un ambito
         *     «tutti».
         * @enum {string}
         */
        AmbitoAzzeramento: "ospite" | "host";
        /** AreaIstatOutput */
        AreaIstatOutput: {
            /** Messaggio */
            messaggio: string;
            motivo: components["schemas"]["Motivo"] | null;
            parametri: components["schemas"]["ParametriIstatOutput"] | null;
            /** Promemoria Manuale */
            promemoria_manuale: boolean;
            stato: components["schemas"]["StatoConfigurazione"];
        };
        /** AreaTassaOutput */
        AreaTassaOutput: {
            /** Messaggio */
            messaggio: string;
            motivo: components["schemas"]["Motivo"] | null;
            parametri: components["schemas"]["ParametriTassaOutput"] | null;
            /** Promemoria Manuale */
            promemoria_manuale: boolean;
            stato: components["schemas"]["StatoConfigurazione"];
        };
        /**
         * AzzeramentoInput
         * @description Chi chiede l'azzeramento (NFR-15). Nient'altro.
         *
         *     Solo l'attore, perché il «cosa» sta nel percorso e il «quando» lo decide
         *     il server: un payload che portasse un nome o un contatto scriverebbe un
         *     dato personale nel log della richiesta, cioè proprio ciò che
         *     l'azzeramento sta per togliere (AD-16, NFR-11).
         */
        AzzeramentoInput: {
            /** Attore */
            attore: string;
        };
        /**
         * AzzeramentoOutput
         * @description L'evidenza, in conteggi e identificatori.
         *
         *     I due conteggi sono distinti e non sommati: «un'anagrafica azzerata» e
         *     «un `sommario` azzerato» sono adempimenti diversi su tabelle diverse, e
         *     un totale unico nasconderebbe il caso in cui uno dei due non è avvenuto —
         *     che è esattamente il buco che questo lotto chiude.
         */
        AzzeramentoOutput: {
            ambito: components["schemas"]["AmbitoAzzeramento"];
            /** Anagrafiche Azzerate */
            anagrafiche_azzerate: number;
            /**
             * Eseguito Il
             * Format: date-time
             */
            eseguito_il: string;
            /**
             * Riferimento
             * Format: uuid
             */
            riferimento: string;
            /** Sommari Azzerati */
            sommari_azzerati: number;
        };
        /**
         * CalendarioOutput
         * @description La griglia unificata: Prenotazioni di tutte le Strutture e i Canali.
         *
         *     Envelope, e per la ragione di sempre: UX-DR6 vuole «dati aggiornati
         *     alle HH:MM» su ogni superficie che mostra dati da Feed, e questa li
         *     mostra da PIÙ Feed insieme.
         *
         *     `ultimo_sync_riuscito_il` è il **meno recente** fra i Feed del
         *     perimetro, non il più recente: la freschezza di una vista aggregata è
         *     quella della sua fonte più vecchia. Prendere il massimo direbbe
         *     all'Host che il calendario è aggiornato a due minuti fa mentre uno dei
         *     due portali non risponde da tre giorni — la falsa sincronia di NFR-2
         *     con l'aggravante di essere aritmeticamente vera.
         *
         *     È `None` appena un Feed del perimetro non ha MAI avuto un sync
         *     riuscito: lì non esiste un orario da mostrare, e il sistema dice «non
         *     lo so» invece di mostrarne uno che parla solo degli altri Feed.
         *
         *     I tre conteggi esistono perché «nessun Feed collegato», «un Feed che
         *     non ha mai importato» e «un Feed in errore» arrivano altrimenti alla
         *     superficie con lo stesso aspetto — timestamp assente — e sono
         *     affermazioni diverse.
         */
        CalendarioOutput: {
            /**
             * A
             * Format: date
             */
            a: string;
            /**
             * Da
             * Format: date
             */
            da: string;
            /** Feed Collegati */
            feed_collegati: number;
            /** Feed In Errore */
            feed_in_errore: number;
            /** Feed Mai Sincronizzati */
            feed_mai_sincronizzati: number;
            stato_sync: components["schemas"]["StatoSincronizzazione"];
            /** Strutture */
            strutture: components["schemas"]["StrutturaDelCalendarioOutput"][];
            /** Ultimo Sync Riuscito Il */
            ultimo_sync_riuscito_il: string | null;
            /** Voci */
            voci: components["schemas"]["VoceCalendarioOutput"][];
        };
        /** CambioPasswordInput */
        CambioPasswordInput: {
            /** Password Attuale */
            password_attuale: string;
            /** Password Nuova */
            password_nuova: string;
        };
        /**
         * CanaleFeed
         * @description Origine delle Prenotazioni importate (FR-4).
         * @enum {string}
         */
        CanaleFeed: "airbnb" | "booking" | "altro";
        /**
         * CanaleNotifica
         * @description Canali di notifica Host dell'MVP (envelope operativo: in-app + email).
         * @enum {string}
         */
        CanaleNotifica: "in_app" | "email";
        /**
         * CategoriaErroreSync
         * @description Categoria dell'errore, mai il dettaglio tecnico (AD-16, NFR-17).
         *
         *     `URL_NON_RAGGIUNGIBILE` copre insieme il fallimento di connessione E il
         *     rifiuto della politica di uscita di rete: l'Host vede lo stesso esito,
         *     così il messaggio d'errore non diventa un canale per scoprire la rete
         *     interna (NFR-17).
         * @enum {string}
         */
        CategoriaErroreSync: "url_non_raggiungibile" | "timeout" | "risposta_troppo_grande" | "esito_http_inatteso" | "feed_non_valido" | "feed_senza_eventi";
        /** ComuneConfigInput */
        ComuneConfigInput: {
            /** Attore */
            attore: string;
            /** Esenzione Eta Max */
            esenzione_eta_max?: number | null;
            /** Esenzione Notti Oltre */
            esenzione_notti_oltre?: number | null;
            /** Tassa Importo Cent */
            tassa_importo_cent: number;
            tassa_periodicita: components["schemas"]["Periodicita"];
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ComuneOutput */
        ComuneOutput: {
            /** Codice Istat */
            codice_istat: string;
            /** Nome */
            nome: string;
            /** Provincia */
            provincia: string;
            /** Regione Codice Istat */
            regione_codice_istat: string;
        };
        /** ConfigSalvataOutput */
        ConfigSalvataOutput: {
            /** Valido Al */
            valido_al: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ConfigurazioneNormativaOutput */
        ConfigurazioneNormativaOutput: {
            /**
             * Alla Data
             * Format: date
             */
            alla_data: string;
            istat: components["schemas"]["AreaIstatOutput"];
            tassa_soggiorno: components["schemas"]["AreaTassaOutput"];
        };
        /** CredenzialiInput */
        CredenzialiInput: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** FeedIcalInput */
        FeedIcalInput: {
            /** @default altro */
            canale: components["schemas"]["CanaleFeed"];
            /**
             * Struttura Id
             * Format: uuid
             */
            struttura_id: string;
            /** Url */
            url: string;
        };
        /** FeedIcalOutput */
        FeedIcalOutput: {
            canale: components["schemas"]["CanaleFeed"];
            categoria_errore: components["schemas"]["CategoriaErroreSync"] | null;
            /**
             * Collegato Il
             * Format: date-time
             */
            collegato_il: string;
            /** Eventi Malformati */
            eventi_malformati: number;
            /** Eventi Ricorrenti Non Espansi */
            eventi_ricorrenti_non_espansi: number;
            /** Fallimenti Consecutivi */
            fallimenti_consecutivi: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prenotazioni Attive */
            prenotazioni_attive: number;
            /** Prenotazioni Rimosse Dal Feed */
            prenotazioni_rimosse_dal_feed: number;
            stato_sync: components["schemas"]["StatoSincronizzazione"];
            /**
             * Struttura Id
             * Format: uuid
             */
            struttura_id: string;
            /** Ultimo Sync Riuscito Il */
            ultimo_sync_riuscito_il: string | null;
            /** Ultimo Tentativo Il */
            ultimo_tentativo_il: string | null;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostOutput */
        HostOutput: {
            canale_notifica_preferito: components["schemas"]["CanaleNotifica"];
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * Motivo
         * @enum {string}
         */
        Motivo: "comune_non_riconosciuto" | "comune_non_configurato" | "regione_non_riconosciuta" | "regione_non_configurata";
        /** ParametriFiscaliInput */
        ParametriFiscaliInput: {
            /** Aliquote Citate */
            aliquote_citate: string;
            /** Attore */
            attore: string;
            /** Regime Da Soglia */
            regime_da_soglia: string;
            /** Regime Sotto Soglia */
            regime_sotto_soglia: string;
            /** Soglia Strutture */
            soglia_strutture: number;
            /** Testo Da Soglia */
            testo_da_soglia: string;
            /** Testo Sotto Soglia */
            testo_sotto_soglia: string;
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** ParametriIstatOutput */
        ParametriIstatOutput: {
            periodicita: components["schemas"]["Periodicita"];
            /** Tracciato */
            tracciato: string;
        };
        /** ParametriTassaOutput */
        ParametriTassaOutput: {
            /** Esenzione Eta Max */
            esenzione_eta_max: number | null;
            /** Esenzione Notti Oltre */
            esenzione_notti_oltre: number | null;
            /** Importo Cent */
            importo_cent: number;
            periodicita: components["schemas"]["Periodicita"];
        };
        /**
         * Periodicita
         * @enum {string}
         */
        Periodicita: "mensile" | "trimestrale" | "semestrale" | "annuale";
        /** PreferenzeInput */
        PreferenzeInput: {
            canale_notifica_preferito: components["schemas"]["CanaleNotifica"];
        };
        /** PrenotazioneOutput */
        PrenotazioneOutput: {
            canale: components["schemas"]["CanaleFeed"];
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Ical Uid */
            ical_uid: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notti */
            notti: number;
            /** Sommario */
            sommario: string | null;
            stato: components["schemas"]["StatoPrenotazione"];
            /**
             * Struttura Id
             * Format: uuid
             */
            struttura_id: string;
        };
        /**
         * PrenotazioniDelFeedOutput
         * @description Prenotazioni di un Feed **con** la loro verità temporale (NFR-2, UX-DR6).
         *
         *     Un envelope e non una lista nuda. UX-DR6 chiede l'etichetta «dati
         *     aggiornati alle HH:MM» su OGNI superficie che mostra dati da Feed, e una
         *     lista nuda di Prenotazioni non ha un posto dove metterla: il consumatore
         *     dovrebbe procurarsi il timestamp da una seconda chiamata e correlarlo a
         *     mano, cioè avrebbe due letture che possono divergere e nessuna che dica
         *     quale delle due vale.
         *
         *     `stato_sync` viaggia insieme per la stessa ragione: senza, un Feed mai
         *     sincronizzato e uno sincronizzato senza prenotazioni arrivano entrambi
         *     come lista vuota e timestamp nullo — e sono affermazioni diverse.
         */
        PrenotazioniDelFeedOutput: {
            /** Prenotazioni */
            prenotazioni: components["schemas"]["PrenotazioneOutput"][];
            stato_sync: components["schemas"]["StatoSincronizzazione"];
            /** Ultimo Sync Riuscito Il */
            ultimo_sync_riuscito_il: string | null;
        };
        /**
         * RegimeFiscaleOutput
         * @description Contenuto informativo con disclaimer: mai un calcolo d'imposta.
         */
        RegimeFiscaleOutput: {
            /** Aliquote Citate */
            aliquote_citate: string | null;
            /** Disclaimer */
            disclaimer: string;
            /** Mostra Pannello Transizione */
            mostra_pannello_transizione: boolean;
            /** Oltre Soglia */
            oltre_soglia: boolean;
            /** Regime */
            regime: string | null;
            /** Soglia */
            soglia: number | null;
            stato: components["schemas"]["StatoRegime"];
            /** Strutture Non Archiviate */
            strutture_non_archiviate: number;
            /** Testo */
            testo: string;
        };
        /** RegioneConfigInput */
        RegioneConfigInput: {
            /** Attore */
            attore: string;
            istat_periodicita: components["schemas"]["Periodicita"];
            /** Istat Tracciato */
            istat_tracciato: string;
            /** Valido Al */
            valido_al?: string | null;
            /**
             * Valido Dal
             * Format: date
             */
            valido_dal: string;
        };
        /** RegioneOutput */
        RegioneOutput: {
            /** Codice Istat */
            codice_istat: string;
            /** Nome */
            nome: string;
        };
        /**
         * StatoConfigurazione
         * @enum {string}
         */
        StatoConfigurazione: "configurata" | "configurazione_non_disponibile";
        /**
         * StatoPrenotazione
         * @description Stati di AD-19: solo `attiva` concorre ai Conflitti.
         *
         *     `rimossa_dal_feed` è la transizione che sostituisce la cancellazione
         *     quando un evento scompare dall'export dell'OTA (AD-4).
         * @enum {string}
         */
        StatoPrenotazione: "attiva" | "cancellata" | "rimossa_dal_feed";
        /**
         * StatoRegime
         * @enum {string}
         */
        StatoRegime: "disponibile" | "configurazione_non_disponibile";
        /**
         * StatoSincronizzazione
         * @description Cosa dire all'Host, compreso il caso «non lo so ancora».
         *
         *     `MAI_SINCRONIZZATO` esiste perché il silenzio ambiguo è il modo in cui la
         *     falsa sincronia fa il danno maggiore: il sistema dice «non so» invece di
         *     lasciar credere che i dati siano aggiornati.
         * @enum {string}
         */
        StatoSincronizzazione: "mai_sincronizzato" | "in_corso" | "riuscito" | "fallito";
        /**
         * StatoStruttura
         * @description Una Struttura si archivia, mai si distrugge (AD-20).
         * @enum {string}
         */
        StatoStruttura: "attiva" | "archiviata";
        /**
         * StrutturaDelCalendarioOutput
         * @description Le Strutture del perimetro, per etichettare le righe della griglia.
         *
         *     Viaggiano dentro la risposta del Calendario e non da una seconda
         *     chiamata: la griglia aggrega più Strutture (FR-4) e senza i nomi
         *     mostrerebbe degli UUID, oppure il client dovrebbe correlare a mano due
         *     letture che possono divergere.
         */
        StrutturaDelCalendarioOutput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
        };
        /** StrutturaInput */
        StrutturaInput: {
            /** Cin */
            cin?: string | null;
            /** Comune */
            comune: string;
            /** Comune Codice Istat */
            comune_codice_istat?: string | null;
            /** Nome */
            nome: string;
            /** Regione */
            regione: string;
        };
        /** StrutturaOutput */
        StrutturaOutput: {
            /** Cin */
            cin: string | null;
            /** Cin Mancante */
            readonly cin_mancante: boolean;
            /** Comune */
            comune: string;
            /** Comune Codice Istat */
            comune_codice_istat: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
            /** Regione */
            regione: string;
            /** Regione Codice Istat */
            regione_codice_istat: string | null;
            stato: components["schemas"]["StatoStruttura"];
        };
        /** StrutturaUpdate */
        StrutturaUpdate: {
            /** Cin */
            cin?: string | null;
            /** Comune */
            comune?: string | null;
            /** Comune Codice Istat */
            comune_codice_istat?: string | null;
            /** Nome */
            nome?: string | null;
            /** Regione */
            regione?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoceCalendarioOutput
         * @description Una Prenotazione come la griglia la mostra (FR-4).
         *
         *     Porta Canale d'origine, Struttura, date **e Ospite**. Tre valori sono
         *     derivati dal server e il frontend li presenta senza ricalcolarli
         *     (AD-14): `notti`, che è la lunghezza dell'intervallo semiaperto
         *     `[check_in, check_out)` di AD-3; `ospite_principale`, che è la scelta
         *     fra più Ospiti registrati; `altri_ospiti`, il loro conteggio.
         *
         *     `ospite_principale` è `None` quando l'Ospite non è noto — e non è un
         *     errore: una Prenotazione senza Ospite resta valida, e la superficie
         *     scrive «Ospite non indicato», mai un segnaposto che somigli a un nome
         *     (NFR-11, AD-21).
         *
         *     `sommario` resta il testo OPACO del portale, dove il portale l'ha
         *     scritto: non è il nome dell'Ospite e non lo diventa passando di qui.
         */
        VoceCalendarioOutput: {
            /** Altri Ospiti */
            altri_ospiti: number;
            canale: components["schemas"]["CanaleFeed"];
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notti */
            notti: number;
            /** Ospite Principale */
            ospite_principale: string | null;
            /** Sommario */
            sommario: string | null;
            stato: components["schemas"]["StatoPrenotazione"];
            /**
             * Struttura Id
             * Format: uuid
             */
            struttura_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredenzialiInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registrazione_api_v1_auth_registrazione_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredenzialiInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    griglia_api_v1_calendario_get: {
        parameters: {
            query: {
                da: string;
                a: string;
                struttura_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarioOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comuni_api_v1_comuni_get: {
        parameters: {
            query: {
                ricerca: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComuneOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lista_api_v1_feed_ical_get: {
        parameters: {
            query: {
                struttura_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedIcalOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collega_api_v1_feed_ical_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedIcalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedIcalOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dettaglio_api_v1_feed_ical__feed_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedIcalOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prenotazioni_api_v1_feed_ical__feed_id__prenotazioni_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrenotazioniDelFeedOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_v1_hosts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
        };
    };
    cambia_password_api_v1_hosts_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioPasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggiorna_preferenze_api_v1_hosts_me_preferenze_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenzeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_comune_api_v1_interno_comuni__codice_istat__configurazione_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                codice_istat: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComuneConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    azzera_ospiti_dell_host_api_v1_interno_host__host_id__azzeramento_ospiti_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                host_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AzzeramentoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AzzeramentoOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    azzera_ospite_api_v1_interno_host__host_id__ospiti__ospite_id__azzeramento_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                host_id: string;
                ospite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AzzeramentoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AzzeramentoOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_parametri_fiscali_api_v1_interno_parametri_fiscali_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParametriFiscaliInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configura_regione_api_v1_interno_regioni__codice_istat__configurazione_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                codice_istat: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegioneConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSalvataOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regime_fiscale_api_v1_regime_fiscale_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeFiscaleOutput"];
                };
            };
        };
    };
    conferma_lettura_api_v1_regime_fiscale_conferma_lettura_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regioni_api_v1_regioni_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegioneOutput"][];
                };
            };
        };
    };
    lista_api_v1_strutture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"][];
                };
            };
        };
    };
    crea_api_v1_strutture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrutturaInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggiorna_api_v1_strutture__struttura_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrutturaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archivia_api_v1_strutture__struttura_id__archivia_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrutturaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configurazione_normativa_api_v1_strutture__struttura_id__configurazione_normativa_get: {
        parameters: {
            query?: {
                alla_data?: string | null;
            };
            header?: never;
            path: {
                struttura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurazioneNormativaOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
